### ISSUE TITLE
Fatal Exception: java.lang.AssertionError: setApiKey() should be called before initialize()!

### ISSUE THREAD

**Issue by vyurking** [Unact/yandex_mapkit#320]
На андроидах иногда ловлю ошибку, что ключ или устанавливается несколько раз или как-то вызывается инициализация несколько раз, Решил форкнуть пакет и сделать установку ключа перед **MapKitFactory.initialize** в файле **YandexMapkitPlugin**,  а не в **MainActivity**,  но при старте приложения все равно ловлю setApiKey несколько раз.
Скрин вывода "принтом" в консоль установки ключа, на котором видно, что приложение устанавливает его несколько раз.
![Снимок экрана 2023-07-05 в 15 21 53](https://github.com/Unact/yandex_mapkit/assets/75477280/4a7b9f61-69ef-4e30-b561-936dcbceaf3c)

Честно, не понимаю в чем проблема :C

Вот так устанавливаю ключ:
```
  private boolean mapinit = false;

  private void initMap(FlutterPluginBinding binding) {
    if (mapinit) {
      return;
    }
    MapKitFactory.setApiKey("КЛЮЧ");
    MapKitFactory.setLocale("ru_RU");
    MapKitFactory.initialize(binding.getApplicationContext());
    mapinit = true;
  }

  @Override
  public void onAttachedToEngine(FlutterPluginBinding binding) {
    initMap(binding);
    BinaryMessenger messenger = binding.getBinaryMessenger();
    binding.getPlatformViewRegistry().registerViewFactory(VIEW_TYPE, new YandexMapFactory(messenger, new LifecycleProvider()));

    setupChannels(messenger, binding.getApplicationContext());
  }

**Comment by DCrow** [comment]
Добрый день!

Инициализировать можно только в MainActivity, как указано в readme.

Пожалуйста приложите `flutter doctor -v` и список используемых плагинов. Также подскажите, проект используется как "Add-to-app" или же обычное флаттер приложение?

**Comment by vyurking** [comment]
Добрый день, у меня обычное flutter приложение.
Вот **flutter doctor -v**: 
```
[✓] Flutter (Channel stable, 3.10.2, on macOS 13.4 22F66 darwin-arm64, locale ru-RU)
    • Flutter version 3.10.2 on channel stable at /Users/vsevolodurkin/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (7 недель назад), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/vsevolodurkin/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/vsevolodurkin/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/223.8836.35.2231.10320515/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/vsevolodurkin/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/223.8836.35.2231.10320515/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.80.0)
```

А вот список плагинов (здесь Ваш пакет форкнут):
```
  battery_plus: 3.0.6
  bloc: 8.1.2
  bloc_concurrency: 0.2.2
  #convert: ^3.1.1
  cupertino_icons: ^1.0.2
  #dart_des: ^1.0.2
  device_info_plus: 9.0.2
  encrypt: 5.0.1
  equatable: 2.0.5
  #flutter_3des: ^0.0.4
  firebase_core: ^2.13.1
  firebase_crashlytics: ^3.3.2
  firebase_performance: ^0.9.2+2
  flutter_bloc: 8.1.3
  #flutter_des: ^2.1.0
  flutter_local_notifications: 9.5.3+1
  flutter_map: ^4.0.0
  flutter_map_marker_cluster: ^1.1.1
  flutter_simple_dependency_injection: 2.0.0
  flutter_slidable: 3.0.0
  flutter_statusbarcolor_ns: 0.5.0
  flutter_svg: any
  grpc: 3.1.0
  html: ^0.15.0
  intl: ^0.17.0
  latlong2: 0.8.1
  mask_text_input_formatter: 2.4.0
  material_color_utilities: 0.2.0
  package_info_plus: ^4.0.2
  path_provider: 2.0.15
  plugin_platform_interface: 2.1.4
  provider: 6.0.5
  qr_code_scanner: 1.0.1
  safe_device: ^1.1.4
  share_plus: 7.0.2
  shared_preferences: ^2.1.1
  simple_json_persistence: 2.1.0+2
  #tripledes_nullsafety: ^1.0.3
  url_launcher: 6.1.11
  uuid: 3.0.7
  vector_graphics: ^1.1.6
  vector_graphics_compiler: ^1.1.6
  #yandex_mapkit: 3.2.0
  yandex_mapkit:
    path: ./yandex_mapkit
```
