### ISSUE TITLE
Android Crash "Error connecting to the service protocol: failed to connect to http://127.0.0.1:56801/eKGQ1WXqNLI=/ the Dart compiler exited unexpectedly."

### ISSUE THREAD

**Issue by starig** [Unact/yandex_mapkit#388]
Здравствуйте!
Подключил yandex_mapkit: ^4.1.0. 
Следовал инструкции на https://pub.dev/. 
С ios версией все работает нормально, но когда пытаюсь запустить приложение на anroid- его моментально крашит.
<img width="852" alt="image" src="https://github.com/user-attachments/assets/24127f6d-72f4-479f-b038-48c504efab39" />

pubspec.yaml: 
```
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.16
  blur: ^4.0.0
  flutter_card_swiper: ^7.0.2
  yandex_mapkit: ^4.1.0
#  yandex_maps_mapkit_lite: ^4.9.0-beta
  sign_in_with_apple: ^6.1.4
  permission_handler: ^11.3.1
  geolocator: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
```

MainActivity.kt
```
package com.example.app_name

import androidx.annotation.NonNull
import com.yandex.mapkit.MapKitFactory
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine

class MainActivity: FlutterActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        MapKitFactory.setLocale("ru_RU")
        MapKitFactory.setApiKey("<TOKEN>")
        super.configureFlutterEngine(flutterEngine)
    }
}
```

build.gradle dependencies
```
dependencies {
    implementation 'com.yandex.android:maps.mobile:4.6.1-full'
}
```

gradle.properties
```
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
yandexMapkit.variant=full
```
