### ISSUE TITLE
Нужно обновить версию equatable 

### ISSUE THREAD

**Issue by kostyanchikoff** [Unact/yandex_mapkit#94]
Многие библиотеки требуют обновленную версию equatable:2.0.0, если вас нет времени я могу закинуть МР

**Comment by DCrow** [comment]
Перевел библиотеку на nullsafety и обновил `equatable`

**Comment by Shalamovvs** [comment]
> Перевел библиотеку на nullsafety и обновил `equatable`

Не подскажите, как скоро обновленная версия библиотеки, появится на pub.dev ?
Благодарю

**Comment by DCrow** [comment]
@Shalamovvs 

Думаю в этом месяце. Если хочется уже использовать, то в `pubspec.yaml` можно указать
```yaml
yandex_mapkit:
    git:
      url: ssh://git@github.com/Unact/yandex_mapkit.git
```
